# Puerto del servidor (default 8080, puedes cambiarlo)
server.port=8080

# Logs más limpios durante el desarrollo
logging.level.com.chat=DEBUG
logging.level.org.springframework.web.socket=INFO

# Exponer Prometheus y otros endpoints de Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true

# Tag global: identifica esta app en Grafana cuando haya varios servicios
management.metrics.tags.application=ws-chat
spring.application.name=ws-chat

# URL del servidor Zipkin
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Porcentaje de operaciones a trazar: 1.0 = 100% (desarrollo), 0.1 = 10% (producción)
management.tracing.sampling.probability=1.0